USE [master]
GO

/****** Object:  Database [Bot]    Script Date: 2023-03-03 16:54:12 ******/
CREATE DATABASE [Bot]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Bot', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Bot.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Bot_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Bot_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Bot].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Bot] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Bot] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Bot] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Bot] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Bot] SET ARITHABORT OFF 
GO

ALTER DATABASE [Bot] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Bot] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Bot] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Bot] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Bot] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Bot] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Bot] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Bot] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Bot] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Bot] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Bot] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Bot] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Bot] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Bot] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Bot] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Bot] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Bot] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Bot] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Bot] SET  MULTI_USER 
GO

ALTER DATABASE [Bot] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Bot] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Bot] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Bot] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Bot] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Bot] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Bot] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Bot] SET  READ_WRITE 
GO


